import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
});
const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: "400",
  style: "normal"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.className} ${ibmPlexMono.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}